server:
  port: 8090
spring:
  application:
    name: apiGateway
  cloud:
    gateway:
      routes:
        - id: Microservice1
          uri: http://localhost:8080/
          predicates:
            - Path=/books/**
            - Path=/accounts/**
        - id: Microservice2
          uri: http://localhost:8081/
          predicates:
            - Path=/admin/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

